src/Feature/ProductCompare/Feature.Compare.Website/Models/AddViewCompareButtonModel.cs
using Sitecore.Commerce.XA.Foundation.Common.Models;
using Sitecore.Data.Items;

namespace Feature.Compare.Website.Models
{
    public class AddViewCompareButtonModel : BaseCommerceRenderingModel
    {
        public string AddToCompareButtonText { get; set; }
        public string ViewCompareButtonText { get; set; }
        public string AddingToCompareWaitText { get; set; }
        public string ComparePageLink { get; set; }
        public bool IsProductInCompareList { get; set; }
        public string CatalogName { get; set; }
        public string ProductId { get; set; }
        public string VarientId { get; set; }
        public bool IsValid { get; set; }

        public void Initialize(Item productItem)
        {
            ProductId = productItem.Name;
        }
    }
}

src/Feature/ProductCompare/Feature.Compare.Website/Models/ProductCompareListItemModel.cs
using Sitecore.Commerce.XA.Feature.Catalog.Models;
using Sitecore.Commerce.XA.Foundation.Common.Models;

namespace Feature.Compare.Website.Models
{
    public class ProductCompareListItemModel : BaseCommerceRenderingModel
    {
        public string  SellableItemId { get; set; }
        public int Depth { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public string EnergyConsumption { get; set; }
        public string EnergyStarRating { get; set; }
        public bool IceDispenser { get; set; }
        public string InternalLighting { get; set; }
        public int Volume { get; set; }
        public CatalogItemRenderingModel CatalogItemRenderingModel { get; set; }
    }
}

src/Feature/ProductCompare/Feature.Compare.Website/Models/ProductCompareModel.cs
using System.Collections.Generic;
using Sitecore.Commerce.XA.Foundation.Common.Models;

namespace Feature.Compare.Website.Models
{
    public class ProductCompareModel : BaseCommerceRenderingModel
    {
        public IList<ProductCompareListItemModel> Products { get; set; }
        public bool IsValid { get; set; }
        public string RemoveFromCompareText { get; set; }
    }
}

src/Feature/ProductCompare/Feature.Compare.Website/Models/RemoveFromProductCompareModel.cs
using System;
using Sitecore.Commerce.Services;
using Sitecore.Commerce.XA.Foundation.Common;
using Sitecore.Commerce.XA.Foundation.Common.Context;
using Sitecore.Commerce.XA.Foundation.Common.Models.JsonResults;

namespace Feature.Compare.Website.Models
{
    public class RemoveFromProductCompareModel : BaseJsonResult
    {
        public string RemovedSellableItemId { get; set; }

        public RemoveFromProductCompareModel(IContext context, IStorefrontContext storefrontContext) : base(context, storefrontContext)
        {
        }

        public RemoveFromProductCompareModel(ServiceProviderResult result, IStorefrontContext storefrontContext, IContext context) : base(result, storefrontContext, context)
        {
        }

        public RemoveFromProductCompareModel(string area, Exception exception, IStorefrontContext storefrontContext, IContext context) : base(area, exception, storefrontContext, context)
        {
        }

        public RemoveFromProductCompareModel(string url, IStorefrontContext storefrontContext) : base(url, storefrontContext)
        {
        }
    }
}

src/Feature/ProductCompare/Feature.Compare.Website/Controllers/ProductCompareController.cs
using System;
using System.Web.Mvc;
using System.Web.UI;
using Feature.Compare.Website.Repositories;
using Sitecore.Commerce.XA.Foundation.Common.Context;
using Sitecore.Commerce.XA.Foundation.Common.Controllers;
using Sitecore.Commerce.XA.Foundation.Common.Models;
using Sitecore.Commerce.XA.Foundation.Common.Models.JsonResults;
using Sitecore.Commerce.XA.Foundation.Connect;

namespace Feature.Compare.Website.Controllers
{
    public class ProductCompareController : BaseCommerceStandardController
    {
        private readonly IProductCompareRepository _productCompareRepository;
        private readonly IVisitorContext _visitorContext;
        private readonly IModelProvider _modelProvider;

        public ProductCompareController(IProductCompareRepository productCompareRepository, IVisitorContext visitorContext, IModelProvider modelProvider, IStorefrontContext storefrontContext, IContext context) : base(storefrontContext, context)
        {
            _productCompareRepository = productCompareRepository;
            _visitorContext = visitorContext;
            _modelProvider = modelProvider;
        }

        [HttpGet]
        public ActionResult ProductCompare()
        {
            return View(GetRenderingView(nameof(ProductCompare)), _productCompareRepository.GetProductCompareModel(StorefrontContext, _visitorContext));
        }

        [HttpGet]
        public ActionResult AddVewCompareButton()
        {
            return View(GetRenderingView(nameof(AddVewCompareButton)), _productCompareRepository.GetAddViewCompareButtonModel(StorefrontContext, _visitorContext));
        }

        [AllowAnonymous]
        [HttpPost]
        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public JsonResult AddProductToCompareList(string addToCompareCatalogName, string addToCompareProductId, string addToCompareVarientId)
        {
            BaseJsonResult baseJsonResult;
            try
            {
                baseJsonResult = _productCompareRepository.AddProductToCompareCollection(StorefrontContext, _visitorContext, addToCompareCatalogName, addToCompareProductId, addToCompareVarientId);
            }
            catch (Exception ex)
            {
                baseJsonResult = _modelProvider.GetModel<BaseJsonResult>();
                baseJsonResult.SetErrors(nameof(AddProductToCompareList), ex);
            }
            return Json(baseJsonResult);
        }

        [AllowAnonymous]
        [HttpPost]
        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public ActionResult RemoveProductFromCompareList(string removeFromCompareProductId)
        {
            BaseJsonResult baseJsonResult;
            try
            {
                baseJsonResult = _productCompareRepository.RemoveProductFromCompareCollection(StorefrontContext, _visitorContext, removeFromCompareProductId);
            }
            catch (Exception ex)
            {
                baseJsonResult = _modelProvider.GetModel<BaseJsonResult>();
                baseJsonResult.SetErrors(nameof(AddProductToCompareList), ex);
            }
            return Json(baseJsonResult);
        }
    }
}

src/Feature/ProductCompare/Feature.Compare.Website/Views/Commerce/ProductCompare/AddVewCompareButton.cshtml

@using System.Web.Mvc.Ajax
@using System.Web.Mvc.Html
@using Sitecore.XA.Foundation.MarkupDecorator.Extensions
@using Sitecore.XA.Foundation.SitecoreExtensions.Extensions
@using Sitecore.Commerce.XA.Foundation.Common.ExtensionMethods
@using Sitecore.Commerce.XA.Feature.Cart.Models
@using Sitecore.Mvc
@model Feature.Compare.Website.Models.AddViewCompareButtonModel

@{
    var viewCompareLinkStyle = Model.IsProductInCompareList ? "" : "none";
    var addToCompareLinkStyle = Model.IsProductInCompareList ? "none" : "";

    if (!Model.IsValid)
    {
        return;
    }
}

<div @Html.Sxa().Component("cxa-addtocompare-component", Model.Attributes) data-cxa-component-class="AddToCompareForm" data-cxa-component-initialized="false" data-cxa-component-type="form">
    @if (!String.IsNullOrWhiteSpace(Model.ErrorMessage))
    {
        <div class="error-message">
            @Model.ErrorMessage
        </div>
    }
    else
    {
        if (Model == null)
        {
            return;
        }

        <div class="component-content" style="display:@addToCompareLinkStyle">
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
                @Html.Hidden("addToCompareProductId", Model.ProductId)
                @Html.Hidden("addToCompareVarientId", Model.VarientId)
                @Html.Hidden("addToCompareCatalogName", Model.CatalogName)
                @Html.AntiForgeryToken()
                @Html.Sitecore().FormHandler()

                <div class="add-to-compare-btn">
                    <button type="submit" class="add-to-compare-btn" data-loading-text="@Model.AddingToCompareWaitText" disabled="disabled">
                        @Model.AddToCompareButtonText
                    </button>
                </div>
            }

        </div>

        <div class="view-product-compare" style="display:@viewCompareLinkStyle">
            <h5>
                <a href="@Model.ComparePageLink" style="float: left; clear: both; margin: 10px 0;">@Model.ViewCompareButtonText</a>
            </h5>
        </div>
    }
</div>

src/Feature/ProductCompare/Feature.Compare.Website/Views/Commerce/ProductCompare/ProductCompare.cshtml

@model Feature.Compare.Website.Models.ProductCompareModel

<div class="product-compare column-splitter">
    <h2>Product Compare</h2>
    @foreach (var product in Model.Products)
    {
        <div id="pc-@product.SellableItemId" class="col-xs-3">
            @Html.Partial("~/Views/Commerce/ProductCompare/_ProductComparePanel.cshtml", product)
        </div>
    }
</div>

src/Feature/ProductCompare/Feature.Compare.Website/Views/Commerce/ProductCompare/_ProductComparePanel.cshtml
@using Sitecore.Commerce.XA.Foundation.Common
@using Sitecore.Commerce.XA.Foundation.Common.ExtensionMethods

@model Feature.Compare.Website.Models.ProductCompareListItemModel
@{
    if (Model == null)
    {
        return;
    }

    var catalogRenderingModel = Model.CatalogItemRenderingModel;
}

<div class="product-summary">
    <div class="photo">
        @if (catalogRenderingModel.CatalogItem != null)
        {
            using (Html.EditFrame(catalogRenderingModel.CatalogItem.Paths.FullPath, Constants.ItemPaths.EditFrameImages))
            {
                if (catalogRenderingModel.Images != null && catalogRenderingModel.Images.Count > 0)
                {
                    <a href="@catalogRenderingModel.Link">
                        <img src="@catalogRenderingModel.Images.FirstOrDefault().GetImageUrl(300, 300)" alt="product image" title="@catalogRenderingModel.DisplayName" />
                    </a>
                }
                else
                {
                    <a href="@catalogRenderingModel.Link">
                        @Html.Sitecore().Field("Image", Html.Sitecore().CurrentItem, new { Parameters = new Sitecore.Collections.SafeDictionary<string> { { "title", @catalogRenderingModel.DisplayName } } })
                    </a>
                }
            }
        }
        else
        {
            if (catalogRenderingModel.Images != null && catalogRenderingModel.Images.Count > 0)
            {
                <a href="@catalogRenderingModel.Link">
                    <img src="@catalogRenderingModel.Images.FirstOrDefault().GetImageUrl(300, 300)" alt="product image" title="@catalogRenderingModel.DisplayName" />
                </a>
            }
            else
            {
                <a href="@catalogRenderingModel.Link">
                    @Html.Sitecore().Field("Image", Html.Sitecore().CurrentItem, new { Parameters = new Sitecore.Collections.SafeDictionary<string> { { "title", @catalogRenderingModel.DisplayName } } })
                </a>
            }
        }
    </div>
    

    <div class="product-info">
        <h5 class="product-title">
            <a href="@catalogRenderingModel.Link">@catalogRenderingModel.DisplayName</a>
        </h5>
    </div>
    
    @{
        var isVariant = catalogRenderingModel.LowestPricedVariantAdjustedPrice.HasValue;
        var listPriceWithCurrency = string.Empty;

        if (isVariant && catalogRenderingModel.LowestPricedVariantListPrice.HasValue)
        {
            listPriceWithCurrency = catalogRenderingModel.LowestPricedVariantAdjustedPriceWithCurrency;
        }
        else
        {
            listPriceWithCurrency = catalogRenderingModel.ListPriceWithCurrency;
        }
    }
        
    <div class="product-compare-details">
        <ul class="compare-list">
            <li class="compare-value">
                <span class="title">Price:</span>
                <span class="value">@listPriceWithCurrency</span>
            </li>
            <li class="compare-value">
                <span class="title">Width:</span>
                @GetIntCompareValue(Model.Width, "mm")
            </li>
            <li class="compare-value">
                <span class="title">Height:</span>
                @GetIntCompareValue(Model.Height, "mm")
            </li>
            <li class="compare-value">
                <span class="title">Depth:</span>
                @GetIntCompareValue(Model.Depth, "mm")
            </li>
            <li class="compare-value">
                <span class="title">Volume:</span>
                @GetIntCompareValue(Model.Volume, "l")
            </li>
            <li class="compare-value">
                <span class="title">Energy Consumption:</span>
                <span class="value">@Model.EnergyConsumption</span>
            </li>
            <li class="compare-value">
                <span class="title">Energy Star Rating:</span>
                <span class="value">@Model.EnergyStarRating</span>
            </li>
            <li class="compare-value">
                <span class="title">Internal Lighting:</span>
                <span class="value">@Model.InternalLighting</span>
            </li>
            <li class="compare-value">
                <span class="title">Ice Dispenser:</span>
                <span class="value">@Model.IceDispenser</span>
            </li>
        </ul>
    </div>
    
    <div class="remove-form" style="float: right; clear: both; width: 230px; margin: 30px 0;">
        @{ var formDisabledAttr = Model.IsEdit ? "disabled" : "";}
        @using (Ajax.BeginForm("RemoveProductFromCompareList", "ProductCompare", null, new AjaxOptions {OnBegin = "RemoveFromCompareForm.SetAddButton", OnSuccess = "RemoveFromCompareForm.OnSuccess", OnFailure = "RemoveFromCompareForm.OnFailure", HttpMethod = "Post"}))
        {
            @Html.ValidationSummary(true)
            @Html.Hidden("removeFromCompareProductId", Model.SellableItemId)
            @Html.AntiForgeryToken()
            <button type="submit" class="remove-from-compare-btn" style="margin-right: 37px;" @formDisabledAttr>Remove from Compare</button>
        }
    </div>
</div>


@helper GetIntCompareValue(int value, string suffix)
{
    if (value != -1)
    {
        <span class="value">@value@suffix</span>
    }
    else
    {
        <span class="value">--</span>
    }
}









<style>
    .product-info {
        height: 90px;
    }

    .product-compare-details {
        margin-top: 10px;    
    }

    .compare-list .title {
        float: left;
        font-weight: bold;
        margin-left: 20px;
        font-size: 0.8em;
    }

    .compare-list .value {
        float: right;
        margin-right: 20px;
    }

    .compare-list .compare-value {
        clear: both;
        height: 20px;
        margin-bottom: 15px;
    }

    .remove-from-compare-btn {
        border: 2px solid #0e909f;
        font-size: 14px !important;
        font-weight: 400;
        text-align: center !important;
        background: #0e909f;
        color: #fff !important;
        text-shadow: none;
        box-shadow: none;
        display: inline-block;
        cursor: pointer;
        border-radius: 4px;
        min-height: 42px;
        height: 42px;
        padding: 8px 25px 8px 25px;
        width: 210px;
    }

    .photo img {
        width: 225px;
    }

    .product-title {
        text-align: center;
    }
</style>